post http://localhost:3000/register
Content-Type: application/json

{
  "username": "akkumar456",
  "name": "224",
  "password": "1215908",
  "gender": "male",
  "location": "Detroit"
}

###
post http://localhost:3000/login
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567"
}

###
put http://localhost:3000/change-password
Content-Type: application/json

{
    "username": "adam_richard",
    "oldPassword": "richard@123",
    "newPassword": "richard@123"
}


